"]" # in terminal to add a pkg 

In [1]:
rand() #random Float64 in [0,1)


0.03508300719716284

In [5]:
collect(1:2)
landed_on_tails = rand([1:2]) == 1



false

In [6]:
landed_on_tailes = rand() < 0.5

true

a Gaussian Number

In [8]:
randn() # n for normal! 

-1.2862236488623147

In [9]:
?randn

search: randn rand transcode macroexpand @macroexpand1 @macroexpand



```
randn([rng=GLOBAL_RNG], [T=Float64], [dims...])
```

Generate a normally-distributed random number of type `T` with mean 0 and standard deviation 1. Optionally generate an array of normally-distributed random numbers. The `Base` module currently provides an implementation for the types [`Float16`](@ref), [`Float32`](@ref), and [`Float64`](@ref) (the default), and their [`Complex`](@ref) counterparts. When the type argument is complex, the values are drawn from the circularly symmetric complex normal distribution.

# Examples

```jldoctest
julia> using Random

julia> rng = MersenneTwister(1234);

julia> randn(rng, ComplexF64)
0.6133070881429037 - 0.6376291670853887im

julia> randn(rng, ComplexF32, (2, 3))
2×3 Array{Complex{Float32},2}:
 -0.349649-0.638457im  0.376756-0.192146im  -0.396334-0.0136413im
  0.611224+1.56403im   0.355204-0.365563im  0.0905552+1.31012im
```


In [10]:
σ² #\sigma tab over  

search:

Couldn't find \sigma
Perhaps you meant @simd, sign or @time


No documentation found.

Binding `\sigma` does not exist.


In [15]:
using Random
x = [1, 2, 3, 4, 5]
shuffle!(x)
x 

5-element Array{Int64,1}:
 1
 2
 5
 4
 3

randomly select form a population with and without replacement 

In [21]:
Pkg.add("Statsbase")

UndefVarError: UndefVarError: Pkg not defined

In [20]:

using Statsbase
groceries = [:chicken, :carrots, :brocolli, :rice]
sample(groceries, 2, replace = true) 

LoadError: syntax: extra token "statsbase" after end of expression

In [22]:
sample(["rain", "cloudy", "sun"], ProbabilityWeights ([0.1, 0.6, 0.3]))

LoadError: syntax: space before "(" not allowed in "ProbabilityWeights ("

mutable vs immutabel 

In [24]:
struct Researcher 
    institution::String 
    nb_pubs::Int
end

publish_a_paper!(researcher::Researcher) = researcher.nb_pubs += 1 

cory = Researcher("OSU", 1) 

Researcher("OSU", 1)

In [25]:
publish_a_paper!(cory) #wont be able to be changed by default 

ErrorException: setfield! immutable struct of type Researcher cannot be changed

In [27]:
mutable struct MutableResearcher 
    institution::String 
    nb_pubs::Int
end

publish_a_paper!(researcher::MutableResearcher) = researcher.nb_pubs += 1 

cory = MutableResearcher("OSU", 1) 

publish_a_paper!(cory)
cory 

MutableResearcher("OSU", 2)

# DATAFRAMES

In [54]:
using Pkg 
Pkg.add("CSV")
Pkg.add("DataFrame")

 Resolving package versions...
  Updating `C:\Users\Owner\.julia\environments\v1.2\Project.toml`
 [no changes]
  Updating `C:\Users\Owner\.julia\environments\v1.2\Manifest.toml`
 [no changes]


Pkg.Types.PkgError: The following package names could not be resolved:
 * DataFrame (not found in project, manifest or registry)
Please specify by known `name=uuid`.

In [55]:
using DataFrame
using CSV 


ArgumentError: ArgumentError: Package DataFrame not found in current path:
- Run `import Pkg; Pkg.add("DataFrame")` to install the DataFrame package.


# construct a 'Dataframe'

In [56]:
city = ["Corvallis", "Portland", "Eugene"]
pop = [57961, 67805, 168916]

df_cities = DataFrame(city=city, pop=pop)
df_cities

3×2 DataFrame
│ Row │ city      │ pop    │
│     │ String    │ Int64  │
├─────┼───────────┼────────┤
│ 1   │ Corvallis │ 57961  │
│ 2   │ Portland  │ 67805  │
│ 3   │ Eugene    │ 168916 │

In [57]:
sort!(pop) #but this sucks because they are out of order now 

3-element Array{Int64,1}:
  57961
  67805
 168916

add rows to DataFrame 

In [58]:
push!(df_cities, ["Bend", 94520])


4×2 DataFrame
│ Row │ city      │ pop    │
│     │ String    │ Int64  │
├─────┼───────────┼────────┤
│ 1   │ Corvallis │ 57961  │
│ 2   │ Portland  │ 67805  │
│ 3   │ Eugene    │ 168916 │
│ 4   │ Bend      │ 94520  │

In [59]:
push!(df_cities, Dict(:pop => 122324, :city => "Berkley"))

5×2 DataFrame
│ Row │ city      │ pop    │
│     │ String    │ Int64  │
├─────┼───────────┼────────┤
│ 1   │ Corvallis │ 57961  │
│ 2   │ Portland  │ 67805  │
│ 3   │ Eugene    │ 168916 │
│ 4   │ Bend      │ 94520  │
│ 5   │ Berkley   │ 122324 │

retrieve a column 

In [60]:
df_cities[:, :pop]

5-element Array{Int64,1}:
  57961
  67805
 168916
  94520
 122324

In [61]:
df_cities.pop

5-element Array{Int64,1}:
  57961
  67805
 168916
  94520
 122324

add columns 

In [62]:
df_cities[!, :state] = ["OR", "OR", "OR", "OR", "CA"]  #! = all the rows 
df_cities

5×3 DataFrame
│ Row │ city      │ pop    │ state  │
│     │ String    │ Int64  │ String │
├─────┼───────────┼────────┼────────┤
│ 1   │ Corvallis │ 57961  │ OR     │
│ 2   │ Portland  │ 67805  │ OR     │
│ 3   │ Eugene    │ 168916 │ OR     │
│ 4   │ Bend      │ 94520  │ OR     │
│ 5   │ Berkley   │ 122324 │ CA     │

In [66]:
insertcols!(df_cities, 1, states= ["OR", "OR", "OR", "OR", "CA"]) # another way to do it 
df_cities

5×4 DataFrame
│ Row │ states │ city      │ pop    │ state  │
│     │ String │ String    │ Int64  │ String │
├─────┼────────┼───────────┼────────┼────────┤
│ 1   │ OR     │ Corvallis │ 57961  │ OR     │
│ 2   │ OR     │ Portland  │ 67805  │ OR     │
│ 3   │ OR     │ Eugene    │ 168916 │ OR     │
│ 4   │ OR     │ Bend      │ 94520  │ OR     │
│ 5   │ CA     │ Berkley   │ 122324 │ CA     │

In [67]:
size(df_cities)

(5, 4)

In [68]:
names(df_cities) #names of columns 

4-element Array{Symbol,1}:
 :states
 :city  
 :pop   
 :state 

###delete rows 

In [69]:
deleterows!(df_cities, 3)
df_cities


4×4 DataFrame
│ Row │ states │ city      │ pop    │ state  │
│     │ String │ String    │ Int64  │ String │
├─────┼────────┼───────────┼────────┼────────┤
│ 1   │ OR     │ Corvallis │ 57961  │ OR     │
│ 2   │ OR     │ Portland  │ 67805  │ OR     │
│ 3   │ OR     │ Bend      │ 94520  │ OR     │
│ 4   │ CA     │ Berkley   │ 122324 │ CA     │

In [70]:
deletecols!(df_cities, 1)

┌ Warning: `deletecols!(df::DataFrame, inds)` is deprecated, use `select!(df, Not(inds))` instead.
│   caller = top-level scope at In[70]:1
└ @ Core In[70]:1


4×3 DataFrame
│ Row │ city      │ pop    │ state  │
│     │ String    │ Int64  │ String │
├─────┼───────────┼────────┼────────┤
│ 1   │ Corvallis │ 57961  │ OR     │
│ 2   │ Portland  │ 67805  │ OR     │
│ 3   │ Bend      │ 94520  │ OR     │
│ 4   │ Berkley   │ 122324 │ CA     │

#iterate through the rows of dataframe 

In [73]:
for row in eachrow(df_cities)
    #row is like a dictionary 
    println("city = ", row[:city])
    println("\tpop = ", row[:pop])
    println("\tstate = ", row[:state])
    
end

city = Corvallis
	pop = 57961
	state = OR
city = Portland
	pop = 67805
	state = OR
city = Bend
	pop = 94520
	state = OR
city = Berkley
	pop = 122324
	state = CA
